name=LiquidCrystal_I2C
version=1.1.2
author=Frank de Brabander
maintainer=Frank de Brabander
sentence=LiquidCrystal Arduino library for I2C LCD displays
paragraph=Library for I2C LCD displays.
category=Display
url=https://github.com/johnrickman/LiquidCrystal_I2C
includes=LiquidCrystal_I2C.h
