"""device_lifecycle_mqtt_fields

Revision ID: 10477b6ee802
Revises: 67a248623c99
Create Date: 2026-03-08 16:57:17.785155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10477b6ee802'
down_revision: Union[str, None] = '67a248623c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create PostgreSQL enum types first
    subscriptionstatus = sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'EXPIRED', name='subscriptionstatus')
    communicationmode = sa.Enum('HTTP', 'MQTT', name='communicationmode')
    subscriptionstatus.create(op.get_bind(), checkfirst=True)
    communicationmode.create(op.get_bind(), checkfirst=True)

    # Add new columns (nullable first)
    op.add_column('devices', sa.Column('assigned_to_plant_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('license_key', sa.String(length=19), nullable=True))
    op.add_column('devices', sa.Column('device_password', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('subscription_status', subscriptionstatus, nullable=True))
    op.add_column('devices', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('communication_mode', communicationmode, nullable=True))

    # Migrate existing secret_key data → license_key format (LIC-XXXX-YYYY-ZZZZ)
    op.execute(
        "UPDATE devices SET license_key = 'LIC-' || SUBSTRING(secret_key, 1, 4) || '-' || "
        "SUBSTRING(secret_key, 5, 4) || '-' || SUBSTRING(secret_key, 9, 4) "
        "WHERE license_key IS NULL"
    )
    # Set defaults for existing devices
    op.execute("UPDATE devices SET subscription_status = 'ACTIVE' WHERE subscription_status IS NULL")
    op.execute("UPDATE devices SET communication_mode = 'HTTP' WHERE communication_mode IS NULL")

    # Now make license_key non-nullable
    op.alter_column('devices', 'license_key', nullable=False)

    # Drop old secret_key constraints and column
    op.drop_constraint('devices_secret_key_key', 'devices', type_='unique')
    op.drop_index('idx_devices_secret_key', table_name='devices')
    op.drop_column('devices', 'secret_key')

    # Create new indexes and constraints
    op.create_index('idx_devices_license_key', 'devices', ['license_key'], unique=False)
    op.create_unique_constraint('uq_devices_license_key', 'devices', ['license_key'])
    op.create_foreign_key('fk_devices_assigned_plant', 'devices', 'plants', ['assigned_to_plant_id'], ['plant_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('secret_key', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_index('idx_devices_license_key', table_name='devices')
    op.create_index('idx_devices_secret_key', 'devices', ['secret_key'], unique=False)
    op.create_unique_constraint('devices_secret_key_key', 'devices', ['secret_key'])
    op.drop_column('devices', 'communication_mode')
    op.drop_column('devices', 'subscription_expires_at')
    op.drop_column('devices', 'subscription_status')
    op.drop_column('devices', 'device_password')
    op.drop_column('devices', 'license_key')
    op.drop_column('devices', 'assigned_to_plant_id')
    # ### end Alembic commands ###
