"""add contact_inquiries table

Revision ID: 27739cc82679
Revises: 019668703033
Create Date: 2026-03-11 23:17:03.161313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27739cc82679'
down_revision: Union[str, None] = '019668703033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('inquiry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inquiry_type', sa.Enum('GENERAL', 'DEMO', 'ENTERPRISE', 'SALES', 'TRIAL', name='inquirytype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('farm_size', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###
