"""initial_tables

Revision ID: 67a248623c99
Revises: 
Create Date: 2026-03-08 14:20:27.161343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a248623c99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('plants',
    sa.Column('plant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('plant_code', sa.String(length=20), nullable=False),
    sa.Column('plant_type', sa.Enum('OYSTER', 'BUTTON', 'SHIITAKE', 'MIXED', name='planttype'), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('plant_size_sqft', sa.Integer(), nullable=True),
    sa.Column('no_of_rooms', sa.Integer(), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('plant_id'),
    sa.UniqueConstraint('plant_code')
    )
    op.create_index('idx_plants_owner', 'plants', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('assigned_plants', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_owner', 'users', ['owner_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'CONFIG_CHANGE', name='auditaction'), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_table', 'audit_log', ['table_name'], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='reporttype'), nullable=False),
    sa.Column('report_name', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.Enum('PDF', 'EXCEL', 'CSV', name='reportformat'), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('room_code', sa.String(length=20), nullable=True),
    sa.Column('room_type', sa.Enum('SPAWN_RUN', 'FRUITING', 'INCUBATION', 'STORAGE', name='roomtype'), nullable=True),
    sa.Column('room_size_sqft', sa.Integer(), nullable=True),
    sa.Column('no_of_racks', sa.Integer(), nullable=True),
    sa.Column('no_of_bags', sa.Integer(), nullable=True),
    sa.Column('bags_per_rack', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.plant_id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_index('idx_rooms_plant', 'rooms', ['plant_id'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('secret_key', sa.String(length=12), nullable=False),
    sa.Column('device_name', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.Enum('ESP32', 'ESP8266', 'ARDUINO', 'PLC', name='devicetype'), nullable=True),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('hardware_version', sa.String(length=20), nullable=True),
    sa.Column('device_ip', sa.String(length=45), nullable=True),
    sa.Column('wifi_rssi', sa.Integer(), nullable=True),
    sa.Column('free_heap', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('secret_key')
    )
    op.create_index('idx_devices_mac', 'devices', ['mac_address'], unique=False)
    op.create_index('idx_devices_room', 'devices', ['room_id'], unique=False)
    op.create_index('idx_devices_secret_key', 'devices', ['secret_key'], unique=False)
    op.create_table('thresholds',
    sa.Column('threshold_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.Enum('CO2', 'HUMIDITY', 'TEMPERATURE', name='thresholdparameter'), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hysteresis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('threshold_id'),
    sa.UniqueConstraint('room_id', 'parameter', name='uq_room_parameter')
    )
    op.create_index('idx_thresholds_room', 'thresholds', ['room_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('CO2_HIGH', 'CO2_LOW', 'TEMP_HIGH', 'TEMP_LOW', 'HUMIDITY_HIGH', 'HUMIDITY_LOW', 'DEVICE_OFFLINE', 'SENSOR_ERROR', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('parameter', sa.String(length=50), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_alerts_room', 'alerts', ['room_id', 'is_resolved', 'created_at'], unique=False)
    op.create_index('idx_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_unread', 'alerts', ['is_read'], unique=False)
    op.create_table('relay_status',
    sa.Column('status_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('relay_type', sa.Enum('CO2', 'HUMIDITY', 'TEMPERATURE', name='relaytype'), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'AUTO', 'SCHEDULE', name='triggertype'), nullable=True),
    sa.Column('trigger_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index('idx_relay_changed', 'relay_status', ['changed_at'], unique=False)
    op.create_index('idx_relay_device', 'relay_status', ['device_id', 'relay_type'], unique=False)
    op.create_table('room_readings',
    sa.Column('reading_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('co2_ppm', sa.Integer(), nullable=True),
    sa.Column('room_temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('room_humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_1', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_2', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_3', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_4', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_5', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_6', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_7', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_8', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_9', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bag_temp_10', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outdoor_temp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('outdoor_humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index('idx_readings_device_time', 'room_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index('idx_readings_room_time', 'room_readings', ['room_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_readings_room_time', table_name='room_readings')
    op.drop_index('idx_readings_device_time', table_name='room_readings')
    op.drop_table('room_readings')
    op.drop_index('idx_relay_device', table_name='relay_status')
    op.drop_index('idx_relay_changed', table_name='relay_status')
    op.drop_table('relay_status')
    op.drop_index('idx_alerts_unread', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index('idx_alerts_room', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_thresholds_room', table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index('idx_devices_secret_key', table_name='devices')
    op.drop_index('idx_devices_room', table_name='devices')
    op.drop_index('idx_devices_mac', table_name='devices')
    op.drop_table('devices')
    op.drop_index('idx_rooms_plant', table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('reports')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_table', table_name='audit_log')
    op.drop_index('idx_audit_created', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_owner', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_plants_owner', table_name='plants')
    op.drop_table('plants')
    op.drop_table('owners')
    # ### end Alembic commands ###
