"""add harvest and growth_cycle tables

Revision ID: 8ed3cd187f87
Revises: 4770d3122eab
Create Date: 2026-03-11 01:29:26.339737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed3cd187f87'
down_revision: Union[str, None] = '4770d3122eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_cycles',
    sa.Column('cycle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_stage', sa.Enum('INOCULATION', 'SPAWN_RUN', 'INCUBATION', 'FRUITING', 'HARVEST', 'IDLE', name='growthstage'), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=True),
    sa.Column('expected_harvest_date', sa.DateTime(), nullable=True),
    sa.Column('target_yield_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index('idx_growth_cycles_active', 'growth_cycles', ['is_active'], unique=False)
    op.create_index('idx_growth_cycles_room', 'growth_cycles', ['room_id'], unique=False)
    op.create_table('harvests',
    sa.Column('harvest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('harvested_at', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='harvestgrade'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('harvest_id')
    )
    op.create_index('idx_harvests_room', 'harvests', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_harvests_room', table_name='harvests')
    op.drop_table('harvests')
    op.drop_index('idx_growth_cycles_room', table_name='growth_cycles')
    op.drop_index('idx_growth_cycles_active', table_name='growth_cycles')
    op.drop_table('growth_cycles')
    # ### end Alembic commands ###
