"""add_firmware_ota_tables

Revision ID: d6969b656e15
Revises: b3ddedb254b2
Create Date: 2026-03-10 23:23:21.616178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6969b656e15'
down_revision: Union[str, None] = 'b3ddedb254b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware',
    sa.Column('firmware_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('firmware_id'),
    sa.UniqueConstraint('version')
    )
    op.add_column('devices', sa.Column('ota_status', sa.String(length=20), nullable=True))
    op.add_column('devices', sa.Column('last_ota_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_ota_at')
    op.drop_column('devices', 'ota_status')
    op.drop_table('firmware')
    # ### end Alembic commands ###
